/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package page;
import Class.Class_akun;
/**
 *
 * @author HP
 */
public class CrudAkun extends javax.swing.JPanel {
//test
    /**
     * Creates new form CrudAkunFrame
     */
    public CrudAkun() {
        initComponents();
        loadData();
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });
        HapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusBtnActionPerformed(evt);
            }
        });
        txt_cariakun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                String searchString = txt_cariakun.getText();
                if (searchString.equals("Cari nama atau username....")) {
                    searchString = "";
                }
                cariakun(searchString);
            }
        });

        // Auto refresh saat halaman dibuka
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentShown(java.awt.event.ComponentEvent evt) {
                loadData();
            }
        });
    }

    private void cariakun(String str) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) TblData.getModel();
        javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> tr = new javax.swing.table.TableRowSorter<>(model);
        TblData.setRowSorter(tr);
        tr.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + str));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        txt_cariakun = new javax.swing.JTextField();
        EditBtn = new javax.swing.JButton();
        HapusBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblData = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        txt_cariakun.setBackground(new java.awt.Color(242, 244, 247));
        txt_cariakun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_cariakun.setForeground(new java.awt.Color(153, 153, 153));
        txt_cariakun.setText("Cari nama atau username....");
        txt_cariakun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariakunActionPerformed(evt);
            }
        });

        EditBtn.setBackground(new java.awt.Color(0, 51, 255));
        EditBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        EditBtn.setForeground(new java.awt.Color(255, 255, 255));
        EditBtn.setText("Edit Akun");

        HapusBtn.setBackground(new java.awt.Color(204, 0, 0));
        HapusBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        HapusBtn.setForeground(new java.awt.Color(255, 255, 255));
        HapusBtn.setText("Hapus Akun");
        HapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txt_cariakun, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(EditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HapusBtn)
                .addGap(20, 20, 20))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HapusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cariakun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 700, -1));

        TblData.setAutoCreateRowSorter(true);
        TblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblData);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 98, 690, 282));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cariakunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariakunActionPerformed
        // 
    }//GEN-LAST:event_txt_cariakunActionPerformed



    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = TblData.getSelectedRow();
        if (selectedRow != -1) {
            try {
                String idStr = TblData.getValueAt(selectedRow, 0).toString();
                int id_user = Integer.parseInt(idStr);
                String username = TblData.getValueAt(selectedRow, 1).toString();
                String password = TblData.getValueAt(selectedRow, 2).toString();
                String role = TblData.getValueAt(selectedRow, 3).toString();

                javax.swing.JFrame topFrame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
                DialogFrame.EditAkunFrame editFrame = new DialogFrame.EditAkunFrame(topFrame, true, id_user, username, password, role);
                editFrame.setLocationRelativeTo(this);
                editFrame.setVisible(true);
                loadData();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data yang dipilih tidak valid: " + e.getMessage());
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih data yang akan diedit terlebih dahulu.");
        }
    }

    public void loadData() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Role");
        
        Class_akun control = new Class_akun();
        java.sql.ResultSet rs = control.getAllAkun();
        try {
            if (rs != null) {
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("id_user"),
                        rs.getString("nama_user"),
                        rs.getString("sandi"),
                        rs.getString("role")
                    });
                }
            }
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
        }
        TblData.setModel(model);
        
        String currentSearch = txt_cariakun.getText();
        if (currentSearch != null && !currentSearch.isEmpty() && !currentSearch.equals("Cari nama atau username....")) {
            cariakun(currentSearch);
        } else {
            javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> tr = new javax.swing.table.TableRowSorter<>(model);
            TblData.setRowSorter(tr);
        }
    }

    private void HapusBtnActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = TblData.getSelectedRow();
        if (selectedRow != -1) {
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus akun ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                try {
                    String idStr = TblData.getValueAt(selectedRow, 0).toString();
                    int id_user = Integer.parseInt(idStr);
                    Class_akun control = new Class_akun();
                    boolean success = control.hapusAkun(id_user);
                    if (success) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Akun berhasil dihapus!");
                        loadData();
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus akun.");
                    }
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih data yang akan dihapus terlebih dahulu.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditBtn;
    private javax.swing.JButton HapusBtn;
    private javax.swing.JTable TblData;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_cariakun;
    // End of variables declaration//GEN-END:variables
}
