/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package page;

import Class.Class_Laporan;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class laporan extends javax.swing.JPanel {
Class_Laporan backendLaporan = new Class_Laporan();
    /**
     * Creates new form Laporan
     */
    public laporan() {
        initComponents();
        loadKategori();
        loadDataAwal();
    }
    private void loadKategori() {
        // Hapus item selain "Semua Kategori" untuk mencegah duplikasi jika terpanggil ulang
        while (FilterKategori.getItemCount() > 1) {
            FilterKategori.removeItemAt(1);
        }

        ResultSet rs = backendLaporan.getKategoriList();
        try {
            while (rs != null && rs.next()) {
                FilterKategori.addItem(rs.getString("kategori"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Method untuk menampilkan data ResultSet ke dalam JTable
     */
    private void tampilDataKeTabel(ResultSet rs) {
        // Bikin struktur kolom tabel baru sesuai desain revisi transaksi
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Kategori");
        model.addColumn("Tipe Transaksi");
        model.addColumn("Tanggal");
        model.addColumn("Jumlah");

        try {
            while (rs != null && rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("kode_barang"),
                    rs.getString("nama_barang"),
                    rs.getString("kategori"),
                    rs.getString("tipe_transaksi"), // "Restok" atau "Jual"
                    rs.getString("tanggal"),
                    rs.getInt("jumlah")
                });
            }
            TblLaporan.setModel(model);
            if (rs != null) rs.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * memuat semua data riwayat transaksi di awal halaman dibuka
     */
    private void loadDataAwal() {
        ResultSet rs = backendLaporan.getAllLaporanTransaksi();
        tampilDataKeTabel(rs);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        FilterKategori = new javax.swing.JComboBox<>();
        UrutBerdasarkan = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FltrDariTanggal = new com.toedter.calendar.JDateChooser();
        FltrSampaiTanggal = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblLaporan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BtnReset = new javax.swing.JButton();
        BtnTampilkan = new javax.swing.JButton();
        LaopranBarangBtn = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(748, 515));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));

        FilterKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua Kategori", " " }));
        FilterKategori.addActionListener(this::FilterKategoriActionPerformed);
        jPanel1.add(FilterKategori);

        UrutBerdasarkan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal Terbaru", "Nama Barang (A-Z)", "Nama Barang (Z-A)", "Tipe Transaksi", "Kategori" }));
        UrutBerdasarkan.addActionListener(this::UrutBerdasarkanActionPerformed);
        jPanel1.add(UrutBerdasarkan);

        jLabel2.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel2.setText("Kategori");
        jPanel1.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel3.setText("Dari Tanggal");
        jPanel1.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel4.setText("Sampai Tanggal");
        jPanel1.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel5.setText("Urutkan Berdasarkan");
        jPanel1.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Filter Laporan Transaksi");
        jPanel1.add(jLabel6);
        jPanel1.add(FltrDariTanggal);
        jPanel1.add(FltrSampaiTanggal);

        add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        TblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblLaporan.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(TblLaporan);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Hasil Laporan Transaksi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        add(jPanel2);

        BtnReset.setText("RESET");
        BtnReset.addActionListener(this::BtnResetActionPerformed);
        add(BtnReset);

        BtnTampilkan.setBackground(new java.awt.Color(0, 51, 255));
        BtnTampilkan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnTampilkan.setForeground(new java.awt.Color(255, 255, 255));
        BtnTampilkan.setText("Tampilkan");
        BtnTampilkan.addActionListener(this::BtnTampilkanActionPerformed);
        add(BtnTampilkan);

        LaopranBarangBtn.setText("Laporan Barang");
        add(LaopranBarangBtn);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        // TODO add your handling code here:
        FilterKategori.setSelectedIndex(0);
        UrutBerdasarkan.setSelectedIndex(0);
        
        // 2. Kosongkan kalender
        FltrDariTanggal.setDate(null);
        FltrSampaiTanggal.setDate(null);
        
        // 3. Tampilkan ulang semua riwayat transaksi seperti semula
        loadDataAwal();
    }//GEN-LAST:event_BtnResetActionPerformed

    private void BtnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTampilkanActionPerformed
        // TODO add your handling code here:
        // Ambil nilai dari UI
        String kategori = null;
        if (FilterKategori.getSelectedItem() != null) {
            kategori = FilterKategori.getSelectedItem().toString();
        }

        String sortBy = null;
        if (UrutBerdasarkan.getSelectedItem() != null) {
            sortBy = UrutBerdasarkan.getSelectedItem().toString();
        }

        // Validasi input tanggal parsial
        if ((FltrDariTanggal.getDate() != null && FltrSampaiTanggal.getDate() == null) || 
            (FltrDariTanggal.getDate() == null && FltrSampaiTanggal.getDate() != null)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Mohon isi kedua rentang tanggal (Dari & Sampai) dengan lengkap.", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Ambil dan konversi tanggal
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dariTgl = null;
        String sampaiTgl = null;

        if (FltrDariTanggal.getDate() != null) {
            dariTgl = sdf.format(FltrDariTanggal.getDate());
        }
        if (FltrSampaiTanggal.getDate() != null) {
            sampaiTgl = sdf.format(FltrSampaiTanggal.getDate());
        }

        // Kirim semua filter ke class backend
        ResultSet rs = backendLaporan.getLaporanTransaksi(kategori, dariTgl, sampaiTgl, sortBy);
        
        // Tampilkan hasilnya ke tabel
        tampilDataKeTabel(rs);
    }//GEN-LAST:event_BtnTampilkanActionPerformed

    private void FilterKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FilterKategoriActionPerformed

    private void UrutBerdasarkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UrutBerdasarkanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UrutBerdasarkanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnTampilkan;
    private javax.swing.JComboBox<String> FilterKategori;
    private com.toedter.calendar.JDateChooser FltrDariTanggal;
    private com.toedter.calendar.JDateChooser FltrSampaiTanggal;
    private javax.swing.JButton LaopranBarangBtn;
    private javax.swing.JTable TblLaporan;
    private javax.swing.JComboBox<String> UrutBerdasarkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
