/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package page;

import server.Koneksi;
import java.awt.Color;
import javax.swing.BorderFactory;
import Class.class_masterBarang;
import Class.Helper;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class masterBarang extends javax.swing.JPanel {

    class_masterBarang mb;

    /**
     * Creates new form masterBarang
     */
    public masterBarang() {
        initComponents();
        customTable();
        mb = new class_masterBarang();

        tableMasterBarang.setModel(mb.modelMaster);
        mb.initTabelMaster(tableMasterBarang);

        mb.tampilKategori(cmbFilter);
        mb.filterTable(cmbFilter);

        // Load Auto Kode & Date
        tfKodeBarang.setText(Helper.generateAutoKode("BRG", "master_barang", "kode_barang", "id_barang", mb.conn));
        tfCreatedAt.setText(Helper.getSystemDate());
        tfKodeBarang.setEditable(false);
        tfCreatedAt.setEditable(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfKodeBarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNamaBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfHargaBeli = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfHargaJual = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfStokAwal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfCreatedAt = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btmEdit = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        cmbKategori = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMasterBarang = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        cmbFilter = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(174, 179, 187), 2, true));

        jLabel2.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        jLabel2.setText("KODE BARANG");

        tfKodeBarang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(174, 179, 187), 1, true));

        jLabel3.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        jLabel3.setText("NAMA BARANG");

        tfNamaBarang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(174, 179, 187), 1, true));

        jLabel4.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        jLabel4.setText("KATEGORI");

        jLabel5.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        jLabel5.setText("HARGA BELI");

        tfHargaBeli.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfHargaBeli.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfHargaBeli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(174, 179, 187), 1, true));

        jLabel6.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        jLabel6.setText("HARGA JUAL");

        tfHargaJual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfHargaJual.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfHargaJual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(174, 179, 187), 1, true));

        jLabel7.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        jLabel7.setText("STOK AWAL");

        tfStokAwal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(174, 179, 187), 1, true));

        jLabel8.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        jLabel8.setText("CREATED AT");

        tfCreatedAt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(174, 179, 187), 1, true));

        btnDelete.setBackground(new java.awt.Color(0, 77, 153));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btmEdit.setBackground(new java.awt.Color(0, 115, 196));
        btmEdit.setForeground(new java.awt.Color(255, 255, 255));
        btmEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editt.png"))); // NOI18N
        btmEdit.addActionListener(this::btmEditActionPerformed);

        btnNew.setBackground(new java.awt.Color(0, 213, 246));
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnNew.addActionListener(this::btnNewActionPerformed);

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Audio", "Aksesoris", "Monitor", "Networking", "Powerbank", "Printer", "Storage ", "Televisi", " ", " " }));

        btnSave.setBackground(new java.awt.Color(0, 157, 215));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/savee.png"))); // NOI18N
        btnSave.addActionListener(this::btnSaveActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(tfHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNamaBarang)
                            .addComponent(cmbKategori, 0, 192, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(35, 35, 35)
                        .addComponent(tfHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfStokAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(35, 35, 35)
                        .addComponent(tfCreatedAt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btmEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfStokAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(tfCreatedAt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(btmEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        tableMasterBarang.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        tableMasterBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableMasterBarang.setAlignmentX(4.0F);
        tableMasterBarang.setAlignmentY(4.0F);
        tableMasterBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableMasterBarang.setGridColor(new java.awt.Color(0, 77, 153));
        tableMasterBarang.setIntercellSpacing(new java.awt.Dimension(0, 4));
        tableMasterBarang.setRowHeight(34);
        tableMasterBarang.setSelectionBackground(new java.awt.Color(0, 77, 153));
        tableMasterBarang.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tableMasterBarang.setShowGrid(false);
        tableMasterBarang.setShowHorizontalLines(true);
        tableMasterBarang.getTableHeader().setResizingAllowed(false);
        tableMasterBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMasterBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMasterBarang);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(174, 179, 187), 2, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Search");

        tfSearch.setForeground(new java.awt.Color(153, 153, 153));
        tfSearch.setText("    Name / Kode");
        tfSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(174, 179, 187), 1, true));
        tfSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfSearchMousePressed(evt);
            }
        });
        tfSearch.addActionListener(this::tfSearchActionPerformed);
        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchKeyReleased(evt);
            }
        });

        cmbFilter.setBackground(new java.awt.Color(0, 77, 153));
        cmbFilter.setForeground(new java.awt.Color(255, 255, 255));
        cmbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FILTER", "Aksesoris", "Elektronik", "Other" }));
        cmbFilter.addActionListener(this::cmbFilterActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfSearch)
                    .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void customTable() {
        tableMasterBarang.getTableHeader().setBackground(Color.decode("#424752"));
        tableMasterBarang.getTableHeader().setForeground(Color.decode("#004D99"));
        tableMasterBarang.getTableHeader().setBorder(BorderFactory.createLineBorder(Color.decode("#004D99")));

    }
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (selectedId == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data dari tabel terlebih dahulu!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            btnDelete.setEnabled(false);

            mb.hapusData(selectedId);

            btnDelete.setEnabled(true);

            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            mb.filterTable(cmbFilter);

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btmEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmEditActionPerformed
        if (selectedId == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data dari tabel terlebih dahulu!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
            String kode = tfKodeBarang.getText().trim();
            String nama = tfNamaBarang.getText().trim();
            String kategori = cmbKategori.getSelectedItem().toString();
            String hargaBeliStr = tfHargaBeli.getText().trim();
            String hargaJualStr = tfHargaJual.getText().trim();
            String stokAwalStr = tfStokAwal.getText().trim();

            if (kode.isEmpty() || nama.isEmpty() || kategori.isEmpty() || hargaBeliStr.isEmpty() || hargaJualStr.isEmpty() || stokAwalStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            int hargaBeli, hargaJual, stokAwal;
            try {
                hargaBeli = Integer.parseInt(hargaBeliStr);
                hargaJual = Integer.parseInt(hargaJualStr);
                stokAwal = Integer.parseInt(stokAwalStr);

                if (hargaBeli < 0 || hargaJual < 0 || stokAwal < 0) {
                    JOptionPane.showMessageDialog(this, "Harga dan stok tidak boleh negatif!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Harga dan Stok harus berupa angka!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            mb.ubahData(selectedId, nama, kategori, hargaBeli, hargaJual, stokAwal);
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
            mb.filterTable(cmbFilter);
        
    }//GEN-LAST:event_btmEditActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        tfKodeBarang.setText(Helper.generateAutoKode("BRG", "master_barang", "kode_barang", "id_barang", mb.conn));
        tfNamaBarang.setText("");
        cmbKategori.setSelectedIndex(0);
        tfHargaBeli.setText("");
        tfHargaJual.setText("");
        tfStokAwal.setText("");
        tfCreatedAt.setText(Helper.getSystemDate());

        tfKodeBarang.setEditable(false);
        tfCreatedAt.setEditable(false);
        tableMasterBarang.clearSelection();
    }//GEN-LAST:event_btnNewActionPerformed


    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchActionPerformed

    private void tfSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSearchMousePressed
        // TODO add your handling code here:
        tfSearch.selectAll();

    }//GEN-LAST:event_tfSearchMousePressed

    private void tfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyReleased
        // TODO add your handling code here:
        tfSearch.setForeground(Color.black);
        mb.cariBarang(tfSearch.getText());

    }//GEN-LAST:event_tfSearchKeyReleased

    private void cmbFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterActionPerformed
        // TODO add your handling code here:
        mb.filterTable(cmbFilter);

    }//GEN-LAST:event_cmbFilterActionPerformed
    int selectedId = 0;
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String kode = tfKodeBarang.getText().trim();
        String nama = tfNamaBarang.getText().trim();
        String kategori = cmbKategori.getSelectedItem().toString();
        String hargaBeliStr = tfHargaBeli.getText().trim();
        String hargaJualStr = tfHargaJual.getText().trim();
        String stokAwalStr = tfStokAwal.getText().trim();

        if (kode.isEmpty() || nama.isEmpty() || kategori.isEmpty() || hargaBeliStr.isEmpty() || hargaJualStr.isEmpty() || stokAwalStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int hargaBeli, hargaJual, stokAwal;
        try {
            hargaBeli = Integer.parseInt(hargaBeliStr);
            hargaJual = Integer.parseInt(hargaJualStr);
            stokAwal = Integer.parseInt(stokAwalStr);

            if (hargaBeli < 0 || hargaJual < 0 || stokAwal < 0) {
                JOptionPane.showMessageDialog(this, "Harga dan stok tidak boleh negatif!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga dan Stok harus berupa angka!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        btnNew.setEnabled(false);

        mb.simpanData(kode, nama, kategori, hargaBeli, hargaJual, stokAwal);

        btnNew.setEnabled(true);

        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
        mb.filterTable(cmbFilter); 
        btnNewActionPerformed(evt);   
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tableMasterBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMasterBarangMouseClicked
        // TODO add your handling code here:
        int row = tableMasterBarang.getSelectedRow();
        if (row != -1) {
            selectedId = Integer.parseInt(tableMasterBarang.getValueAt(row, 0).toString());
            tfKodeBarang.setText(tableMasterBarang.getValueAt(row, 1).toString());
            tfNamaBarang.setText(tableMasterBarang.getValueAt(row, 2).toString());
            Object kat = tableMasterBarang.getValueAt(row, 3);
            if (kat != null) {
                cmbKategori.setSelectedItem(kat.toString());
            }
            tfHargaBeli.setText(tableMasterBarang.getValueAt(row, 4).toString());
            tfHargaJual.setText(tableMasterBarang.getValueAt(row, 5).toString());
            tfStokAwal.setText(tableMasterBarang.getValueAt(row, 6).toString());
            tfCreatedAt.setText(tableMasterBarang.getValueAt(row, 7).toString());

            tfKodeBarang.setEditable(false);
        }
    }//GEN-LAST:event_tableMasterBarangMouseClicked

    private void btnUpdateActionPerformed() {
        if (selectedId == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data dari tabel terlebih dahulu!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmEdit;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbFilter;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMasterBarang;
    private javax.swing.JTextField tfCreatedAt;
    private javax.swing.JTextField tfHargaBeli;
    private javax.swing.JTextField tfHargaJual;
    private javax.swing.JTextField tfKodeBarang;
    private javax.swing.JTextField tfNamaBarang;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfStokAwal;
    // End of variables declaration//GEN-END:variables
}
