/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package page;
import Class.class_stokOpname;
import Class.Helper;

/**
 *
 * @author HP
 */
public class stokOpname extends javax.swing.JPanel {
    class_stokOpname rs;
    /**
     * Creates new form stockOpname
     */
    public stokOpname() {
        initComponents();
        lblKode.setVisible(false);
        rs = new class_stokOpname();
        hilangkanPencarian();
        tabelPencarian.setModel(rs.modelSearch);
        
        // Load Auto Kode & Date
        tfNoTransaksi.setText(Helper.generateAutoKode("OP", "stock_opname", "no_transaksi", "id_stock_opname", rs.conn));
        tfTanggalMasuk.setText(Helper.getSystemDate());

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        // Auto refresh saat halaman dibuka
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tfNoTransaksi.setText(Helper.generateAutoKode("OP", "stock_opname", "no_transaksi", "id_stock_opname", rs.conn));
                tfTanggalMasuk.setText(Helper.getSystemDate());
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfTanggalMasuk = new javax.swing.JTextField();
        tfNoTransaksi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfKeterangan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        scrollPanePencarian = new javax.swing.JScrollPane();
        tabelPencarian = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        tfNamaBarang = new javax.swing.JTextField();
        btnSearch = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        lblKode = new javax.swing.JLabel();
        tfQty = new javax.swing.JSpinner();
        tfStokSistem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(174, 179, 187), 2, true));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 77, 153));
        jLabel1.setText("Informasi Transaksi");

        jLabel2.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel2.setText("Tanggal Sto");

        tfTanggalMasuk.setEditable(false);
        tfTanggalMasuk.setForeground(new java.awt.Color(102, 102, 102));
        tfTanggalMasuk.setText("    12/12/2012");
        tfTanggalMasuk.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(174, 179, 187), 1, true));
        tfTanggalMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfTanggalMasukMousePressed(evt);
            }
        });
        tfTanggalMasuk.addActionListener(this::tfTanggalMasukActionPerformed);

        tfNoTransaksi.setEditable(false);
        tfNoTransaksi.setForeground(new java.awt.Color(102, 102, 102));
        tfNoTransaksi.setText("  1");
        tfNoTransaksi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(174, 179, 187), 1, true));
        tfNoTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfNoTransaksiMousePressed(evt);
            }
        });
        tfNoTransaksi.addActionListener(this::tfNoTransaksiActionPerformed);

        jLabel3.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel3.setText("No. Transaksi");

        tfKeterangan.setForeground(new java.awt.Color(102, 102, 102));
        tfKeterangan.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfKeterangan.setText("    Opsional");
        tfKeterangan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(174, 179, 187), 1, true));
        tfKeterangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfKeteranganMousePressed(evt);
            }
        });
        tfKeterangan.addActionListener(this::tfKeteranganActionPerformed);

        jLabel4.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel4.setText("Keterangan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tfTanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tfNoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tfKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTanggalMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(tfNoTransaksi))
                        .addGap(37, 37, 37))))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(174, 179, 187), 2, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 77, 153));
        jLabel5.setText("Input Barang");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 19, -1, -1));

        jLabel6.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel6.setText("Nama Barang");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 55, -1, -1));

        jLabel7.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel7.setText("Stok di Gudang");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 55, -1, -1));

        tabelPencarian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelPencarian.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelPencarian.setGridColor(new java.awt.Color(0, 98, 135));
        tabelPencarian.setName(""); // NOI18N
        tabelPencarian.setRowHeight(25);
        tabelPencarian.setRowMargin(8);
        tabelPencarian.setSelectionBackground(new java.awt.Color(0, 77, 153));
        tabelPencarian.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelPencarian.setShowGrid(false);
        tabelPencarian.setShowHorizontalLines(true);
        tabelPencarian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelPencarianMousePressed(evt);
            }
        });
        scrollPanePencarian.setViewportView(tabelPencarian);

        jPanel2.add(scrollPanePencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 127, 239, 88));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(174, 179, 187), 1, true));

        tfNamaBarang.setForeground(new java.awt.Color(102, 102, 102));
        tfNamaBarang.setText("  Nama Barang");
        tfNamaBarang.setBorder(null);
        tfNamaBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfNamaBarangMousePressed(evt);
            }
        });
        tfNamaBarang.addActionListener(this::tfNamaBarangActionPerformed);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSearchMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(tfNamaBarang, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 82, -1, -1));

        btnCancel.setBackground(new java.awt.Color(255, 0, 0));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("X");
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        jPanel2.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        lblKode.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        lblKode.setForeground(new java.awt.Color(102, 102, 102));
        lblKode.setText("Kode : ");
        jPanel2.add(lblKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 8, -1, -1));

        tfQty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(174, 179, 187), 1, true));
        tfQty.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(tfQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 82, 159, 33));

        tfStokSistem.setEditable(false);
        jPanel2.add(tfStokSistem, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 160, 34));

        jLabel8.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel8.setText("Stok Sistem");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 133, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 201, -1, 246));

        jButton1.setBackground(new java.awt.Color(0, 77, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/savee.png"))); // NOI18N
        jButton1.setText("SIMPAN TRANSAKSI");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 453, -1, 34));
    }// </editor-fold>//GEN-END:initComponents

    private void tfTanggalMasukMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTanggalMasukMousePressed
        // TODO add your handling code here:
        tfTanggalMasuk.selectAll();
    }//GEN-LAST:event_tfTanggalMasukMousePressed

    private void tfTanggalMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTanggalMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTanggalMasukActionPerformed

    private void tfNoTransaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNoTransaksiMousePressed
        // TODO add your handling code here:
        tfNoTransaksi.selectAll();
    }//GEN-LAST:event_tfNoTransaksiMousePressed

    private void tfNoTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoTransaksiActionPerformed

    private void tfKeteranganMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfKeteranganMousePressed
        // TODO add your handling code here
        tfKeterangan.selectAll();
    }//GEN-LAST:event_tfKeteranganMousePressed

    private void tfKeteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKeteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKeteranganActionPerformed

    private void tabelPencarianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPencarianMousePressed
        // TODO add your handling code here:
        int baris = tabelPencarian.getSelectedRow();
        if (baris != -1) {
            lblKode.setVisible(true);
            String namaBarang = tabelPencarian.getValueAt(baris, 0).toString();
            tfNamaBarang.setText(namaBarang);
            rs.setKode(namaBarang, lblKode);
            
            int idBarang = rs.getBarangIdByNama(namaBarang);
            if (idBarang != -1) {
                int systemStock = rs.getStokSistem(idBarang);
                tfStokSistem.setText(String.valueOf(systemStock));
            }
        }
    }//GEN-LAST:event_tabelPencarianMousePressed

    private void tfNamaBarangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNamaBarangMousePressed
        // TODO add your handling code here:
        tfNamaBarang.selectAll();
    }//GEN-LAST:event_tfNamaBarangMousePressed

    private void tfNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaBarangActionPerformed

    private void btnSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMousePressed
        // TODO add your handling code here:
        rs.cariBarang(tfNamaBarang.getText());
        tabelPencarian.setModel(rs.modelSearch);
        tampilkanPencarian();
    }//GEN-LAST:event_btnSearchMousePressed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        hilangkanPencarian();
        tfNamaBarang.requestFocus();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tampilkanPencarian() {
        scrollPanePencarian.setVisible(true);
        tabelPencarian.setVisible(true);
        btnCancel.setVisible(true);
        revalidate();
        repaint();
    }

    private void hilangkanPencarian() {

        tabelPencarian.setVisible(false);
        scrollPanePencarian.setVisible(false);
        btnCancel.setVisible(false);

    }

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {
        String noTransaksi = tfNoTransaksi.getText().trim();
        String namaBarang = tfNamaBarang.getText().trim();
        int stokDiGudang = ((Number) tfQty.getValue()).intValue();
        String keterangan = tfKeterangan.getText().trim();
        String tanggal = tfTanggalMasuk.getText().trim();

        // Validasi nama barang
        if (namaBarang.isEmpty() || namaBarang.equals("Nama Barang")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih nama barang dari daftar pencarian!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi stok di gudang
        if (stokDiGudang < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Stok di gudang tidak boleh negatif!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi no transaksi
        if (noTransaksi.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No. Transaksi tidak boleh kosong!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (rs.simpanTransaksi(noTransaksi, namaBarang, stokDiGudang, keterangan, tanggal)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Transaksi stok opname berhasil disimpan!");
            tfNoTransaksi.setText(Helper.generateAutoKode("OP", "stock_opname", "no_transaksi", "id_stock_opname", rs.conn));
            tfTanggalMasuk.setText(Helper.getSystemDate());
            tfNamaBarang.setText("  Nama Barang");
            tfQty.setValue(0);
            tfKeterangan.setText("    Opsional");
            tfStokSistem.setText("");
            lblKode.setVisible(false);
            hilangkanPencarian();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblKode;
    private javax.swing.JScrollPane scrollPanePencarian;
    private javax.swing.JTable tabelPencarian;
    private javax.swing.JTextField tfKeterangan;
    private javax.swing.JTextField tfNamaBarang;
    private javax.swing.JTextField tfNoTransaksi;
    private javax.swing.JSpinner tfQty;
    private javax.swing.JTextField tfStokSistem;
    private javax.swing.JTextField tfTanggalMasuk;
    // End of variables declaration//GEN-END:variables
}
