/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Component;

/**
 *
 * @author HP
 */
public class headerPanel extends javax.swing.JPanel {

    /**
     * Creates new form Header
     */
    public headerPanel() {
        initComponents();
        TambahBtn.setVisible(false);
    }

    public void setTitle(String title) {
        lblLocation.setText(title);
    }

    /** Tampilkan username dan role di header setelah login */
    public void setUserInfo(String username, String role) {
        UsernameTxt.setText(username);

        // Warna badge role
        java.awt.Color roleColor;
        switch (role.toLowerCase()) {
            case "admin": roleColor = new java.awt.Color(0, 77, 153);   break; // biru
            case "staff": roleColor = new java.awt.Color(0, 140, 70);   break; // hijau
            case "boss":  roleColor = new java.awt.Color(120, 40, 160); break; // ungu
            default:      roleColor = new java.awt.Color(100, 100, 100); break;
        }
        RoleTxt.setText(role.toUpperCase());
        RoleTxt.setForeground(roleColor);
        RoleTxt.setFont(new java.awt.Font("Inter", java.awt.Font.BOLD, 11));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        RoleTxt = new javax.swing.JLabel();
        TambahBtn = new javax.swing.JButton();
        UsernameTxt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 77, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("APLIKASI ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 77, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("GUDANG");

        jLabel1.setBackground(new java.awt.Color(0, 77, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 77, 153));
        jLabel1.setText("AG");

        setBackground(new java.awt.Color(247, 249, 252));
        setPreferredSize(new java.awt.Dimension(732, 113));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLocation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLocation.setText("DASHBOARD");
        add(lblLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 57, 228, 20));

        RoleTxt.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        RoleTxt.setForeground(new java.awt.Color(102, 102, 102));
        RoleTxt.setText("ROLE");
        add(RoleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 20));

        TambahBtn.setBackground(new java.awt.Color(0, 51, 255));
        TambahBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TambahBtn.setForeground(new java.awt.Color(255, 255, 255));
        TambahBtn.setText("+   Tambah Akun");
        TambahBtn.addActionListener(this::TambahBtnActionPerformed);
        add(TambahBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 175, 37));

        UsernameTxt.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        UsernameTxt.setText("USER NAME");
        add(UsernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account_circle.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 22, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void TambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahBtnActionPerformed
        javax.swing.JFrame topFrame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        DialogFrame.TambahAkunFrame tambahFrame = new DialogFrame.TambahAkunFrame(topFrame, true);
        tambahFrame.setLocationRelativeTo(this);
        tambahFrame.setVisible(true);

        // Refresh CrudAkun table after adding account
        refreshCrudAkun(topFrame);
    }//GEN-LAST:event_TambahBtnActionPerformed
    private void refreshCrudAkun(java.awt.Container container) {
        if (container == null) {
            return;
        }
        for (java.awt.Component comp : container.getComponents()) {
            if (comp instanceof page.CrudAkun) {
                ((page.CrudAkun) comp).loadData();
                return;
            } else if (comp instanceof java.awt.Container) {
                refreshCrudAkun((java.awt.Container) comp);
            }
        }
    }

    public void showAddAccountButton(boolean visible) {
        TambahBtn.setVisible(visible);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RoleTxt;
    private javax.swing.JButton TambahBtn;
    private javax.swing.JLabel UsernameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblLocation;
    // End of variables declaration//GEN-END:variables
}
